### ISSUE TITLE
DefaultComponentManager with MariaDB

### ISSUE THREAD

**Issue by Loneth** [freya022/BotCommands#104]
i test it with PostgresSQL and it's working, but when i use MariaDB (with HikariCP) i got error message and stopping when generating table "version"

```
java.sql.SQLSyntaxErrorException: (conn=31) You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'drop sequence if exists group_seq cascade;

create table if not exists Versio...' at line 2
        at org.mariadb.jdbc.export.ExceptionFactory.createException(ExceptionFactory.java:282)
        at org.mariadb.jdbc.export.ExceptionFactory.create(ExceptionFactory.java:370)
        at org.mariadb.jdbc.message.ClientMessage.readPacket(ClientMessage.java:134)
        at org.mariadb.jdbc.client.impl.StandardClient.readPacket(StandardClient.java:883)
        at org.mariadb.jdbc.client.impl.StandardClient.readResults(StandardClient.java:822)
        at org.mariadb.jdbc.client.impl.StandardClient.readResponse(StandardClient.java:741)
        at org.mariadb.jdbc.client.impl.StandardClient.execute(StandardClient.java:665)
        at org.mariadb.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:92)
        at org.mariadb.jdbc.ClientPreparedStatement.execute(ClientPreparedStatement.java:271)
        at com.zaxxer.hikari.pool.ProxyPreparedStatement.execute(ProxyPreparedStatement.java:44)
        at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.execute(HikariProxyPreparedStatement.java)
        at com.freya02.botcommands.api.components.DefaultComponentManager.resetTables(DefaultComponentManager.java:467)
        at com.freya02.botcommands.api.components.DefaultComponentManager.setupTables(DefaultComponentManager.java:431)
        at com.freya02.botcommands.api.components.DefaultComponentManager.<init>(DefaultComponentManager.java:56)
        at saha.Main.main(Main.java:45)
```

**Comment by freya022** [comment]
MariaDB does not seem to know the `cascade` keyword (at least when deleting sequences)
I'd recommend staying with PostgreSQL as it is what I tested the framework with.

**Comment by freya022** [comment]
Here are several options:
- Use PostgreSQL, at least you wont have any issues with it
- Use V3 pre-releases, not sure if it works on other databases but it's worth a shot
  - Note that the database setup process isn't the same at all, if you choose to try then let me know
- Keep using V2, you can try to work around the issue by:
  - Running [these statements](https://github.com/freya022/BotCommands/blob/7e5d553588aa7e1def370081a76233d2361a55fb/src/main/resources/com/freya02/botcommands/api/components/resetTables.sql#L4-L11) (do not run the two first `drop`s), then run [this script](https://github.com/freya022/BotCommands/blob/7e5d553588aa7e1def370081a76233d2361a55fb/src/main/resources/com/freya02/botcommands/api/components/setup.sql) in your SQL console
  - This should set up your database without running the statements your database do not fully support

**Comment by freya022** [comment]
As official support for other databases is not planned, you are limited to these options, for further discussion about *this topic* I invite anyone to join [the Discord server](https://discord.gg/frpCcQfvTz)
